version: "3.9"
services:
  backend:
    image: ${DOCKER_REGISTRY}/skyeye-backend
    env_file: .env
    restart: on-failure
    volumes:
      - static:/app/static
  frontend:
    image: ${DOCKER_REGISTRY}/skyeye-frontend
    restart: on-failure
    env_file: .env
    volumes:
      - dist:/app/dist
      - ./prev_dist:/app/prev_dist
  ml-task:
    image: ${DOCKER_REGISTRY}/skyeye-ml-task
    restart: on-failure
    ports:
      - "${ENGINE_PORT}:5000"
    runtime: nvidia
  database:
    image: "postgres:12.11-alpine3.16"
    restart: on-failure
    env_file: .env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
  server:
    image: caddy:2.6.2-alpine
    ports:
      - "${FRONTEND_PORT}:80"
    volumes:
            - ./config/Caddyfile:/etc/caddy/Caddyfile
            - dist:/usr/share/caddy/frontend
            - static:/usr/share/caddy/django_static/static
            - caddy_data:/data
            - caddy_config:/config
    depends_on:
      - frontend
      - backend
volumes:
  static: {}
  dist: {}
  caddy_data: {}
  caddy_config: {}
